// === Comic Backgrounds ===
export const comicBackgrounds = [
  'https://amelia-i.com/wp-content/uploads/2025/04/ChatGPT-Image-Apr-26-2025-01_47_50-PM.png',
  'https://amelia-i.com/wp-content/uploads/2025/04/ChatGPT-Image-Apr-26-2025-01_53_02-PM.png',
  'https://amelia-i.com/wp-content/uploads/2025/04/ChatGPT-Image-Apr-26-2025-02_07_01-PM.png',
  'https://amelia-i.com/wp-content/uploads/2025/04/ChatGPT-Image-Apr-26-2025-03_07_32-PM.png',
  'https://amelia-i.com/wp-content/uploads/2025/04/ChatGPT-Image-Apr-26-2025-03_08_26-PM.png',
  'https://amelia-i.com/wp-content/uploads/2025/04/ChatGPT-Image-Apr-26-2025-03_11_32-PM.png',
  'https://amelia-i.com/wp-content/uploads/2025/04/ChatGPT-Image-Apr-26-2025-03_12_37-PM.png',
  'https://amelia-i.com/wp-content/uploads/2025/04/ChatGPT-Image-Apr-26-2025-03_24_42-PM.png',
  'https://amelia-i.com/wp-content/uploads/2025/04/ChatGPT-Image-Apr-26-2025-03_30_24-PM.png',
  'https://amelia-i.com/wp-content/uploads/2025/04/ChatGPT-Image-Apr-26-2025-03_32_31-PM.png',
  'https://amelia-i.com/wp-content/uploads/2025/04/ChatGPT-Image-Apr-26-2025-03_33_57-PM.png'
];

// === Phone Number Entry Prompts ===
export const phonePrompts = [
  "Wanna fly this thing? Flash me your digits, stud.",
  "Pilot privileges? You gotta give it up — your number, that is.",
  "Don't be shy. What's your number, gorgeous?",
  "Type those digits slow... we’re watching.",
  "No number, no fun. Fork it over.",
  "Come on, I don't bite (unless you're into that). Drop your number.",
  "Make it official. Put your number where your mouth is.",
  "One ride, one number. That's the deal.",
  "Numbers first, regrets later.",
  "I'm not that easy. I need your number first.",
  "Let’s make this official. Your number, please. 😘",
  "Trust me — it's easier if you just hand it over.",
  "Digits now, airplane later.",
  "Give me your number. I promise not to text at 2AM... probably.",
  "Consent is sexy. Tap in those digits, baby.",
  "Your phone number turns me on. Aviation mode ON.",
  "Let’s start with the important stuff. Numbers first.",
  "What’s your phone number? Asking for... flight purposes. 😉",
  "Seduce me with your area code.",
  "Numbers, not feelings. Let’s go.",
  "Don't leave me on read. Type your number.",
  "This isn’t Tinder. We require digits upfront.",
  "Airplanes are sexy. So are accurate phone numbers.",
  "Show me you’re serious. Type those 10 digits.",
  "You think you can fly this without dropping digits? Cute.",
  "Give me your number — I’ll show you my tail number.",
  "Make it official. Digits or disqualified.",
  "You’ll need more than good looks. Start typing, ace.",
  "We like pilots who commit. Number, please.",
  "Permission to taxi... once you give me your number.",
  "You can't ride this plane without a number, cowboy.",
  "I love a pilot who knows their digits.",
  "You’re cleared for takeoff... pending digits.",
  "Aviation is a commitment. Numbers first, romance later.",
  "Don’t tease me — type it in.",
  "We take your digits very seriously. Mostly.",
  "Numbers unlock airplanes. And hearts.",
  "We promise not to drunk dial... often.",
  "Commitment looks good on you. Number, please.",
  "First rule of flight club? Always leave your number.",
  "Swipe right. Leave your number. Fly high.",
  "Your future CFI is judging your typing skills right now.",
  "Your mom told you not to give out your number. She was wrong.",
  "Nothing serious. Just a quick number and a couple thousand feet AGL.",
  "Fly me to the moon... but first, your number.",
  "Paperwork is sexy. Numbers too.",
  "How do you like your phone numbers? Digits first, regrets later.",
  "Is that a number in your pocket or are you just happy to fly?",
  "Don’t leave me hanging. Drop the digits.",
  "Put the phone where your mouth is. Kidding. Type it in, stud.",
  "I swear this number stays between us... and the airplane.",
  "Numbers make the world go 'round. And pilots go fly.",
  "You can’t just be hot — you gotta type too.",
  "Earn your wings. Start with your digits.",
  "The only thing sexier than 100LL? A good area code. 🔥"
];

// === No Phone Number Entered Prompts ===
export const noPhonePrompts = [
  "You can't fly without leaving a number, Maverick.",
  "Even Goose entered his phone number. C'mon.",
  "What are we supposed to call, the Tower?",
  "Phone number, or no clearance for takeoff!",
  "Without digits, you're grounded.",
  "Is this an invisible ink test? Because I see no number.",
  "Phone first. Plane later.",
  "Flight plans require contact info, ace.",
  "No digits, no runway clearance.",
  "Not even Skynet can find you without a number.",
  "You're taxiing without clearance, pilot.",
  "I can't read minds, only numbers.",
  "Insert digits before takeoff.",
  "Pilot error: missing number.",
  "You're a ghost on my radar screen.",
  "Houston, we have a missing number.",
  "Your co-pilot entered his number. What's your excuse?",
  "The runway is closed until you check in.",
  "Emergency checklist item 1: Phone number.",
  "You must declare a number before flight.",
  "Who you gonna call? ...Nobody, apparently.",
  "Flight instructor needs your digits, ace.",
  "Without a number, you're lost in the Bermuda Triangle.",
  "Request denied: No contact info submitted.",
  "You just got bumped to stand-by. Try again.",
  "Please refile your flight plan with your number attached.",
  "Cleared to nowhere without a phone number.",
  "Skipping the digits? Grounded.",
  "We lost you at hello.",
  "This is Mission Control. Enter your number to continue."
];

// === No Student Found Prompts ===
export const noStudentFoundPrompts = [
  "That number’s not cleared for takeoff. 🚫",
  "Phone number not found... maybe it’s flying solo? 🛫",
  "Houston, we have a wrong number. 📞",
  "That’s not a number we have on the flight deck. 🤔",
  "No student found... did you stow away? 😅",
  "Hmm, our radar’s not picking that up. 📡",
  "Are you calling from Area 51? 👽",
  "This number isn’t filed on our flight plan. 🗺️",
  "Number rejected. Try again, Maverick. 🕶️",
  "Flight crew doesn’t recognize that call sign. 📻"
];

// === Oops Messages (No Flight Found) ===
export const oopsMessages = [
  "Oops, I pulled a Maverick again.",
  "Did I forget to file my flight plan?",
  "No appointment? Classic.",
  "Maybe I dreamed my flight schedule.",
  "Well, this is awkward.",
  "Checking... still no flight. Still awkward.",
  "I'm just here for the free coffee.",
  "Somebody moved my appointment!",
  "Maybe Skynet deleted my flight?",
  "Houston, we have a scheduling issue.",
  "Scheduling is a suggestion, right?",
  "Lost in the hangar again.",
  "Searching... searching... nope.",
  "My flight must be stealth-mode today.",
  "Could’ve sworn I booked this!",
  "Let's blame ATC for this one.",
  "Flight plans are for quitters.",
  "Just vibing near airplanes.",
  "The tower lost my request.",
  "Still holding short, no clearance.",
  "Pre-flighting... my excuses.",
  "Maybe I’m invisible today?",
  "Flight schedule: TBD!",
  "Oops. Wrong airport maybe?",
  "Plot twist: No appointment needed?",
  "Maybe the dog ate my appointment.",
  "Clear skies... unclear plans.",
  "Manual override initiated!",
  "My instructor forgot too, right?",
  "I swear it was on my calendar!",
  "Alternate mission: Find donuts.",
  "The plane is calling my name anyway.",
  "Emergency checklist: Book appointment.",
  "Just passing through... or am I?",
  "Alternate flight plan activated.",
  "Self-dispatcher training in progress.",
  "Calendar turbulence detected.",
  "Abort? Retry? Proceed?",
  "Time flies when you’re unbooked.",
  "Hangar surfing now.",
  "Lost flight? Found excuses!",
  "Dispatch Center must be playing hide and seek.",
  "Unofficial squadron leader today.",
  "I’m early. Or late. Or… something.",
  "Manifest destiny: Check-out anyway!",
  "Maybe I’m scheduled in another dimension.",
  "Plan B: Wing it.",
  "Plan C: Hope for the best.",
  "Chart not found. Compass spinning."
];

// checkoutReminders.js
export const checkoutReminders = [
  "Don’t ghost us — check back in or we’re charging you like it’s a rental car.",
  "Flight’s booked, now don’t forget the return trip — or it’s a full block bill.",
  "Don’t vanish like a magician. We review every checkout.",
  "Hey Maverick — bring the bird back and log that flight, or it’s a 2-hour invoice.",
  "Check-in or checkbook. Your choice. 😎",
  "We love you, but we will invoice you.",
  "You’re good to go — but we’ll expect you back. Log it or pay max block.",
  "It’s not personal. It’s policy. No check-in? Full block billed.",
  "We review every checkout. Yes, even yours, Top Gun.",
  "Our system has one rule: No check-in, no mercy.",
  "Think of check-in like flossing. It saves you pain later.",
  "Your Hobbs time starts now — just remember to stop it with a check-in.",
  "Unless you’re mid-emergency landing… check back in.",
  "This isn’t Southwest. We know who you are. Check in or it’s full price.",
  "Don’t make us use the calculator. Log the flight, avoid the fright.",
  "Don’t make accounting cry. Just check in.",
  "Every unlogged flight adds five gray hairs to our maintenance team.",
  "No check-in? We'll assume you flew to Kansas for barbecue.",
  "Save your wallet, save our logs. Check back in.",
  "Check-ins are sexy. Be sexy.",
  "Cross-country or not, don’t forget to land AND log.",
  "Be the student your CFI brags about. Check. Back. In.",
  "If you’re reading this, you’re already winning. Just check in and seal the deal.",
  "Billing doesn’t sleep. Neither does the check-in clock.",
  "Like your favorite instructor says: log it or lose it.",
  "Forget to check in once, shame on you. Forget twice, and it’s $89/hour.",
  "You're wheels-up now — but we expect wheels-down and check-in.",
  "Imagine the invoice... now go check back in when you’re done.",
  "The aircraft has a schedule. You have a check-in. Don’t forget it.",
  "Checking in completes the circle of trust.",
  "No check-in? We assume you’re on a sightseeing tour to Tulsa.",
  "Yes, we’re watching. No, we’re not judging. Just check in.",
  "If you leave us hanging, we leave you with a bill.",
  "You wouldn’t leave the master switch on. Don’t skip check-in either.",
  "Finish strong — check back in and fly another day.",
  "Planes have logs. Pilots do too.",
  "Do the right thing. The fun thing. The check-in thing.",
  "This is your subtle-but-not-subtle nudge: check in.",
  "Flying is freedom. Billing is not. Check in.",
  "That checkout was smooth. Don’t ghost the return.",
  "Think of check-in like “wheels down.” It completes the mission.",
  "Help us help you not get billed for four hours. Check in.",
  "One check-in a day keeps the admin away.",
  "No check-in? We assume you’re doing laps over Spirit of St. Louis.",
  "Just because you checked out doesn’t mean billing clocked out.",
  "Your plane will miss you. But accounting misses your check-in more.",
  "You’re airborne now, but don’t forget to land your time block.",
  "Flying is fun. Forgetting to check in? Expensive fun.",
  "Legendary pilots finish their flights *and* their check-ins.",
  "You’re cleared for takeoff — just don’t forget to close the loop."
];

// === Profile Photo Tips ===
export const profilePhotoTips = [
  "Good lighting makes you look like a snack. Step outside.",
  "Look straight at the camera — like you're challenging it to a duel.",
  "Glasses on if you always wear them. Off if you're just feeling cute.",
  "Hats off, hotshot.",
  "We love your style, but no sunglasses, no filters, no masks.",
  "Show your whole face — forehead to chin, don't crop yourself.",
  "Try not to look like you're being arrested. Smile optional.",
  "Selfie mode ON. Angles and bathroom mirrors OFF.",
  "Make sure the camera can see BOTH your eyes, cowboy.",
  "No weird shadows — unless you want Azure to think you’re Bigfoot.",
  "Treat this like a hot date, not a mugshot.",
  "If you’re blurry, we’re billing you emotionally.",
  "You’ll thank yourself later if you take 5 extra seconds for this.",
  "Show us the money-maker: your beautiful face.",
  "Face the light, don’t hide in it. You’re not Batman.",
  "Take it straight on. No glamour shots, Top Gun.",
  "Do it once, do it right — or redo it 7 times later.",
  "Selfie filters = instant face match failure.",
  "No sideways hats unless you’re also flying a time machine.",
  "Make eye contact with the camera — it loves you.",
  "Make sure no walls, ceilings, or cats block your gorgeous mug.",
  "You're a pilot, not a vampire — step into the light.",
  "If your grandma wouldn’t recognize you, Azure won’t either.",
  "We believe in you. Channel your inner Top Gun poster.",
  "If you look like a mystery on a dating app... retake it.",
  "Stand still. Strike a pose. Get your checkout flowin’.",
  "Bad selfies cost good money. Good selfies cost nothing.",
  "Front camera, forehead included, dignity optional.",
  "Remember: No selfie, no flyie.",
  "You have two missions: fly safe and snap smart."
];

// === Selfie Retake Prompts ===
export const selfieRetakePrompts = [
  "That wasn’t a selfie — that was a cryptid sighting. Try again.",
  "Oof. That face match result just called you 'blurry stranger.'",
  "Let’s pretend that didn’t happen. Snap it again, beauty queen.",
  "Face not detected. Neither was confidence. Let’s retake it.",
  "Are you in witness protection? Because Skynet doesn’t recognize you.",
  "Try taking it without the sunglasses. Or the shadow. Or the mystery.",
  "Did you just sneeze mid-snap? One more time, pilot.",
  "We love you, but that one’s going in the blooper reel.",
  "It's a face match, not a haunted mirror test. Retake time.",
  "Give it some light, give it some love — try again.",
  "You’re a 10 but Skynet thinks you’re a glitch.",
  "Selfie tip: Pretend you're actually trying. Retry.",
  "Strike a pose. One that actually shows your face.",
  "That photo scared our AI. Let’s try again with less shadow.",
  "You’re not getting billed for bad selfies, but we’re tempted.",
  "Skynet said ‘meh.’ You deserve better. Let’s get a clearer shot.",
  "Facial recognition requires… a face. Help us help you.",
  "That was either a potato or a human. Try again, hero.",
  "Let’s retake that with more ‘pilot’ and less ‘shadow figure.’",
  "That angle made you look like a mailbox. Try again.",
  "More light. Less mystery. Let’s go.",
  "Let’s see your face, not your forehead and ceiling fan.",
  "You’re cleared for takeoff... once we confirm it’s actually you.",
  "Skynet is picky. But also right. Hit retake.",
  "Not bad, but not good enough. Snap again, Top Gun.",
  "Not every face can be recognized in darkness. Try light this time.",
  "You’re not Medusa. A direct gaze won’t turn us to stone. Look forward.",
  "Give the AI something to work with, not a puzzle.",
  "We swear we’re not judging… Okay, maybe a little. Retry.",
  "Look directly at the lens. This isn’t a modeling shoot. Unless… 👀"
];

// === Security Word Setup Tips ===
export const securityWordSetupTips = [
  "Choose wisely — this word unlocks your wings.",
  "Think call sign, not calculus. One simple word.",
  "Pick something you won’t forget mid-flight.",
  "Keep it simple, slick. No spaces, no weird codes.",
  "Make it personal. Make it memorable. Make it yours.",
  "You’ll need this every checkout. Tattoo it in your brain.",
  "No cheat sheets. One word you’d trust with your airplane.",
  "One secret word. Infinite flight hours.",
  "Taco? Whiskey? Maverick? Whatever you’ll actually remember.",
  "Not your ATM pin. Not your birthday. Something FUN.",
  "Your pilot identity begins here. One strong word.",
  "Pick a word even Skynet would approve of.",
  "Think: what would Goose pick? (Probably 'Danger'.)",
  "You can’t fly if you can’t remember this. Choose well.",
  "All pilots have call signs. This is yours now.",
  "A good word = smooth checkouts forever.",
  "Pick something that makes you grin when you type it.",
  "Nobody wants to be the 'forgot password' student.",
  "Fly smart. Start with a good secret word.",
  "If you wouldn't shout it across a hangar, maybe rethink it.",
  "This is your badge of honor. And your key to fly.",
  "One good word = endless adventures.",
  "Choose a word your CFI would high-five you for.",
  "Not 'password123'. You're better than that.",
  "Fly fast. Think smart. Pick a good code.",
  "Write it in your brain, not on your forehead.",
  "Make future-you proud. Pick something you won't forget.",
  "T-Rex, Bravo, Nacho, Whiskey...your destiny awaits.",
  "One small word for you, one giant leap for your pilot life.",
  "If you forget this word, the ops team gets your cookies."
];

// === Security Word Confirm Prompts ===
export const securityWordConfirmPrompts = [
  "What's the secret password, Maverick?",
  "Whisper your security word, legend.",
  "Confirm your top secret code, pilot.",
  "Flash that security word like a runway beacon.",
  "What magic word gets you cleared for takeoff?",
  "Tell me the code that proves you're one of us.",
  "Agent, state your clearance password.",
  "What's the one word that unlocks your wings?",
  "Give it up, cowboy — password, please.",
  "Say the thing you promised you'd remember. 😉",
  "Your mission, should you choose to accept it: password.",
  "Without the secret word, you can't check out the bird. 😎",
  "What's your call sign, captain?",
  "Unlock your destiny with a single word.",
  "Security check: password, or no flight today.",
  "Confirm your flight credentials — what’s the code?",
  "The runway’s waiting — so’s your password.",
  "Be the pilot your dog thinks you are. Say the word.",
  "One small word for man, one giant leap for checkout.",
  "Don't make us call Skynet. What's your code word?"
];

export const taglines = [
  "Cleared for takeoff... if you survive the paperwork.",
  "The flight deck is calling — don't ghost it.",
  "Pilots who check out, check back in. 😉",
  "Today's forecast: 100% chance of awesome.",
  "Check-outs are sexy. Be sexy.",
  "Channel your inner Maverick.",
  "It's a great day to not get billed extra.",
  "Log it, love it, fly it.",
  "Cleared to proceed... with paperwork.",
  "Make your CFI proud today."
];

// === Random Spinner GIFs ===
export const spinnerGIFs = [
  "http://amelia-i.com/wp-content/uploads/2025/04/Flying-Tom-Cruise-GIF-by-Regal.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/pilot-airplane-GIF.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/night-airplane-GIF.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/celeb-plane-GIF.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/flying-Robert-Hays-GIF.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/lipstick-airplane-movie-GIF.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/i-am-serious-leslie-nielsen-GIF.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/Well-He-Wasnt-Lying-Harrison-Ford-GIF.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/plane-GIF-by-Tara.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/travel-smile-GIF-by-Robert-E-Blackmon.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/plane-GIF.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/fly-flying-GIF-by-Discovery-Europe.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/alaska-GIF.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/Naked-Gun-Movie-GIF.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/i-am-serious-leslie-nielsen-GIF-1.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/Episode-4-Snl-GIF-by-Saturday-Night-Live.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/Fail-Watch-Out-GIF.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/Tunnel-Pass-GIF-by-Red-Bull.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/plane-airplane-GIF.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/Plane-Airplane-GIF-2.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/Soul-Plane-GIF-by-Showmax.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/airport-dancing-GIF.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/airplane-luggage-GIF.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/Black-And-White-Vintage-GIF-by-General-Electric.gif",
  "http://amelia-i.com/wp-content/uploads/2025/04/Fail-Watch-Out-GIF.gif"
  ];

// confirmationPrompts.js
export const confirmationPrompts = [
  "Preflight check complete. You’re cleared for awesome!",
  "Make sure your headset's charged. This flight’s gonna rock. 🎧",
  "Flight suit not required... but highly encouraged. 🕶️",
  "Rest your wings. You’re about to soar. 🛫",
  "You just booked with the coolest school in the Midwest. 💥",
  "Epic flight confirmed. Time to feel like Maverick. 🕺",
  "Bring snacks. But not too many — weight & balance. ⚖️",
  "Bookmark the sky. You’re heading there soon.",
  "Student → Pilot in progress. 🧠 ✈️ 💪",
  "Don’t forget your shades. You’ll be flying above the clouds. 😎",
  "Preflight check complete. You’re cleared for awesome! ✈️",
  "Make sure your headset’s charged. This flight’s gonna rock. 🎧",
  "Flight suit not required... but highly encouraged. 🕶️",
  "Rest your wings. You’re about to soar. 🛫",
  "You just booked with the coolest school in the Midwest. 💥",
  "Epic flight confirmed. Time to feel like Maverick. 🕺",
  "Bring snacks. But not too many – weight & balance. ⚖️",
  "Bookmark the sky. You’re heading there soon. 📘✈️",
  "Student ➜ Pilot in progress. 🧑‍✈️🛫💪",
  "Don’t forget your shades. You’ll be flying above the clouds. 😎",
  "Autopilot status: CONFIDENCE. 🧠",
  "Checklist says: Booked ✔️ Fuel ⛽ Bravery 💯",
  "Flight approved. Tower says ‘You got this.’ 🎤",
  "Another step closer to your wings. 🪽",
  "Sky’s the limit? Not anymore. 🚀",
  "Thrust set. Altitude ready. Let’s go. 🔥",
  "You just leveled up in life. 📶✈️",
  "Runway waiting. Adventure activated. 🛬",
  "Callsign: Badass. Mission: Learn to fly. 🎯",
  "Flight mode: Engaged. 📲🛫",
  "Nothing but blue skies from here. 🌤️",
  "Roger that. Appointment booked. 📡",
  "Buckle up. You’re on the fast track. 🎢",
  "Permission to rock the skies? Granted. 🎸🛫",
  "Simulators can't contain your energy. 🎮➡️✈️",
  "Your propeller might spin faster than your brain. 🌀",
  "Let’s make some crosswinds jealous. 🌬️",
  "Wings ready. Attitude: full send. 🤘",
  "Clear left, clear right… clear for awesomeness. 🫡",
  "Scheduled. And we didn’t even need ATIS. 📻",
  "Final approach to epic achieved. 🎯🛬",
  "Ground school in the rear view. Let’s fly! 🎓✈️",
  "V1, Rotate... Fly! 📈",
  "Sky traffic has been warned. ⚠️",
  "Wheels up, worries down. ✌️",
  "There’s jet fuel in your coffee today. ☕🔥",
  "If flying was easy, everyone would do it. Oh wait, YOU are. 😏",
  "You’ve entered the chat: 'Pilot in training'. 💬🛩️",
  "No autopilot needed for this move. You did it. 🛠️",
  "Booked a flight, and now you're strutting like a CFI. 💃🧑‍🏫",
  "That’s one small click for man, one giant leap toward your checkride. 🌕",
  "Hey student pilot, your wings are showing. 🪽",
  "You're going places... literally. 🌍🛫",
  "Next up: Aviator sunglasses and confident walk. 😎👟",
  "Confirmed flight. Fuel up your confidence. ⛽❤️",
  "Spin checks done. Confidence level: Unlimited. 🔄",
  "Your compass just spun 360 from excitement. 🧭",
  "High pressure system of excitement moving in. ⛅",
  "Caution: Flight schedule may cause spontaneous dancing. 💃🕺",
  "Wind shear won’t stop you now. 🌀🛫",
  "Your call sign should be: Captain Swagger. 🧢",
  "That flight time won’t log itself! 📝🛫",
  "Book. Fly. Repeat. 🔁✈️",
  "Your runway to greatness has just been cleared. 🛣️🛫",
  "Fuel tanks full. Ready for anything. ⛽✅",
  "You just booked a flight. All engines GO. 🔥",
  "Sky’s jealous you’re flying in it. 🌌",
  "You smell that? Smells like flight time. 👃🛫",
  "Taxiing toward legendary status. 🚕🧑‍✈️",
  "Booking complete. Altitude pending. 📍⏫",
  "Not all heroes wear capes… some wear headsets. 🎧🦸",
  "From ground-bound to sky-bound. You’re doing it. 🛫",
  "You make gravity nervous. 🧲😱",
  "Today’s forecast: 100% chance of awesomeness. 🌦️➡️☀️",
  "It's official: Your schedule is now cooler than everyone else’s. 🗓️❄️",
  "If you had wings before, now they're titanium. 🪽🛠️",
  "Autopilot is jealous of your flight instincts. 🤖🧠",
  "Nice job, Captain Cool. 😎🧑‍✈️",
  "Tower says: Cleared to dominate the skies. 🗼👊",
  "You just got airborne in life. 💨",
  "Some book meetings, you book adventures. 💼➡️✈️",
  "Hot prop spinning, cold air blasting. Let’s go. ❄️🔁",
  "This ain’t turbulence, it’s adrenaline. 💥",
  "Flight log updated: Legend in progress. 📖🛫",
  "You should charge rent for how much you're living in the clouds. ☁️💸",
  "Hangar envy begins... now. 🛩️😮",
  "Your checklist: Awesome. Confidence. Flight time. ✅",
  "You just gave gravity a complex. 🔺",
  "You're not in Kansas anymore. You’re in 3,000 AGL. 🌪️🛫",
  "There’s no ceiling to your progress... except maybe Class A airspace. ☁️🧠",
  "One click for you, one huge move for pilotkind. 👨‍🚀✈️",
  "Next stop: Crosswind landings and radio swagger. 🎙️",
  "The wings are jealous of your ambition. 🪽🔥",
  "Wheels up. Attitude up. Let’s go. ⬆️🛫",
  "Just remember: Piston pilots do it better. 😉",
  "Ground school called. They’re proud of you. 📚❤️",
  "Your new ringtone? 'Clear prop!' 🔊",
  "Who needs sidewalks? You're walking on air now. 🏙️",
  "This is the kind of confirmation message you show your friends. 🧾🧑‍✈️",
  "All rise for the honorable Lord of Lift. 🏛️🪂",
  "You’ve earned your stripes. Even if they’re metaphorical. 🎖️"
];

