// phonePrompts.js

export const phonePrompts = [
  "Wanna fly this thing? Flash me your digits, stud.",
  "Pilot privileges? You gotta give it up — your number, that is.",
  "Don't be shy. What's your number, gorgeous?",
  "Type those digits slow... we’re watching.",
  "No number, no fun. Fork it over.",
  "Come on, I don't bite (unless you're into that). Drop your number.",
  "Make it official. Put your number where your mouth is.",
  "One ride, one number. That's the deal.",
  "Numbers first, regrets later.",
  "I'm not that easy. I need your number first.",
  "Let’s make this official. Your number, please. 😘",
  "Trust me — it's easier if you just hand it over.",
  "Digits now, airplane later.",
  "Give me your number. I promise not to text at 2AM... probably.",
  "Consent is sexy. Tap in those digits, baby.",
  "Your phone number turns me on. Aviation mode ON.",
  "Let’s start with the important stuff. Numbers first.",
  "What’s your phone number? Asking for... flight purposes. 😉",
  "Seduce me with your area code.",
  "Numbers, not feelings. Let’s go.",
  "Don't leave me on read. Type your number.",
  "This isn’t Tinder. We require digits upfront.",
  "Airplanes are sexy. So are accurate phone numbers.",
  "Show me you’re serious. Type those 10 digits.",
  "You think you can fly this without dropping digits? Cute.",
  "Give me your number — I’ll show you my tail number.",
  "Make it official. Digits or disqualified.",
  "You’ll need more than good looks. Start typing, ace.",
  "We like pilots who commit. Number, please.",
  "Permission to taxi... once you give me your number.",
  "You can't ride this plane without a number, cowboy.",
  "I love a pilot who knows their digits.",
  "You’re cleared for takeoff... pending digits.",
  "Aviation is a commitment. Numbers first, romance later.",
  "Don’t tease me — type it in.",
  "We take your digits very seriously. Mostly.",
  "Numbers unlock airplanes. And hearts.",
  "We promise not to drunk dial... often.",
  "Commitment looks good on you. Number, please.",
  "First rule of flight club? Always leave your number.",
  "Swipe right. Leave your number. Fly high.",
  "Your future CFI is judging your typing skills right now.",
  "Your mom told you not to give out your number. She was wrong.",
  "Nothing serious. Just a quick number and a couple thousand feet AGL.",
  "Fly me to the moon... but first, your number.",
  "Paperwork is sexy. Numbers too.",
  "How do you like your phone numbers? Digits first, regrets later.",
  "Is that a number in your pocket or are you just happy to fly?",
  "Don’t leave me hanging. Drop the digits.",
  "Put the phone where your mouth is. Kidding. Type it in, stud.",
  "I swear this number stays between us... and the airplane.",
  "Numbers make the world go 'round. And pilots go fly.",
  "You can’t just be hot — you gotta type too.",
  "Earn your wings. Start with your digits.",
  "The only thing sexier than 100LL? A good area code. 🔥"
];

