<?php
function sendEmailNotification($toEmail, $data) {
  $mailgunApiKey = '71d471182ca5a3a56c2ed8d94c537137-e71583bb-1c483164';
  $mailgunDomain = 'mg.amelia-i.com';

  $flightType   = $data['flight_type'] ?? 'Flight';
  $studentName  = $data['student_name'] ?? 'N/A';
  $tail         = $data['tail_number'] ?? 'N/A';
  $cfiName      = $data['cfi_name'] ?? 'N/A';
  $cfiPhone     = $data['cfi_phone'] ?? '';
  $start        = date("D M j, Y g:i A", strtotime($data['start']));
  $end          = date("g:i A", strtotime($data['end']));
  $startRaw     = $data['start'];
  $endRaw       = $data['end'];

  $calendarUrl = sprintf(
    "https://www.google.com/calendar/render?action=TEMPLATE&text=%s&dates=%s/%s&details=%s&location=%s",
    rawurlencode("Piston Flight - $flightType"),
    date('Ymd\THis\Z', strtotime($startRaw)),
    date('Ymd\THis\Z', strtotime($endRaw)),
    rawurlencode("Tail: $tail\nInstructor: $cfiName $cfiPhone\nStudent: $studentName"),
    rawurlencode("Piston Aviation")
  );

  $subject = stripos($flightType, 'CANCELLED') !== false
    ? "🔔 Flight Cancellation - $flightType - $studentName"
    : "🛫 Flight Scheduled - $flightType - $studentName";

  $html = "
  <div style='font-family: Arial, sans-serif; font-size: 16px; line-height: 1.6; color: #333; padding: 20px; border-radius: 8px; background: #f9fafb; border: 1px solid #ddd;'>
    <h2 style='color: " . (stripos($flightType, 'CANCELLED') !== false ? '#dc2626' : '#1e40af') . "; margin-top: 0;'>{$subject}</h2>
    <p><strong>🧑‍✈️ Student:</strong> {$studentName}</p>
    <p><strong>🛫 Flight Type:</strong> {$flightType}</p>
    <p><strong>✈️ Aircraft:</strong> {$tail}</p>
    <p><strong>👨‍🏫 Instructor:</strong> {$cfiName} {$cfiPhone}</p>
    <p><strong>📅 Date:</strong> {$start} – {$end}</p>";

  if (!empty($data['canceled_reason'])) {
    $html .= "<p><strong>❌ Reason:</strong> {$data['canceled_reason']}</p>";
  }

  if (!empty($data['deleted_by'])) {
    $html .= "<p><strong>🗑️ Cancelled By:</strong> {$data['deleted_by']}</p>";
  }

  $html .= "
    <div style='margin-top: 30px; display: flex; gap: 20px; flex-wrap: wrap;'>
      <a href='{$calendarUrl}' target='_blank' style='text-decoration: none;'>
        <div style='background: #1e40af; color: white; padding: 12px 20px; border-radius: 6px; font-weight: bold;'>📆 Add to Google Calendar</div>
      </a>
      <a href='https://pistonup.com' target='_blank' style='text-decoration: none;'>
        <div style='background: #f59e0b; color: black; padding: 12px 20px; border-radius: 6px; font-weight: bold;'>🧢 Get Your Piston Merch</div>
      </a>
    </div>

    <p style='margin-top: 40px; color: #666; font-size: 14px;'>This message was auto-generated by <strong>Piston Aviation</strong>'s scheduling system.<br>You're not just flying — you're flexin'.</p>
  </div>";

  $postData = [
    'from' => 'Piston Scheduler <no-reply@' . $mailgunDomain . '>',
    'to' => $toEmail,
    'subject' => $subject,
    'html' => $html
  ];

  $ch = curl_init();
  curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
  curl_setopt($ch, CURLOPT_USERPWD, 'api:' . $mailgunApiKey);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_POST, 1);
  curl_setopt($ch, CURLOPT_URL, "https://api.mailgun.net/v3/{$mailgunDomain}/messages");
  curl_setopt($ch, CURLOPT_POSTFIELDS, $postData);
  $result = curl_exec($ch);
  curl_close($ch);

  file_put_contents(__DIR__ . '/email_debug.log', date('c') . " | To: $toEmail | Result: $result\n", FILE_APPEND);
}
